# Generated by Django 3.2.8 on 2021-12-15 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20211214_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='bio',
            new_name='user_bio',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='image',
            new_name='user_bio_image',
        ),
    ]
