# Generated by Django 3.2.8 on 2021-12-15 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20211215_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_bio_image',
        ),
    ]
