# Generated by Django 3.2.8 on 2021-12-20 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_delete_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('subject', models.CharField(max_length=25)),
                ('sender', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
    ]
