# Generated by Django 3.2.8 on 2021-12-26 14:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date_sent',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
