# Generated by Django 3.2.8 on 2022-01-02 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_contact_date_sent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Message'},
        ),
    ]
