# Generated by Django 3.2.8 on 2021-11-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('is_customer', 'Customer'), ('is_vendor', 'Vendor')], max_length=25),
        ),
    ]
