# Generated by Django 3.2.8 on 2021-11-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('is_admin', 'Admin'), ('is_customer', 'Customer'), ('is_vendor', 'Vendor')], max_length=25),
        ),
    ]
