# Generated by Django 3.2.8 on 2021-12-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20211126_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=40, unique=True, verbose_name='Username'),
        ),
    ]
