# Generated by Django 3.2.8 on 2021-11-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0002_auto_20211127_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
