# Generated by Django 3.2.8 on 2021-11-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0006_alter_testimonial_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='user_rating',
            field=models.CharField(choices=[('1', '1 star'), ('2', '2 stars'), ('3', '3 stars'), ('4', '4 stars'), ('5', '5 stars')], max_length=150),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='user_testimonial',
            field=models.TextField(),
        ),
    ]
