# Generated by Django 3.2.8 on 2021-11-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0008_alter_testimonial_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='user_testimonial',
            field=models.TextField(max_length=254),
        ),
    ]
