# Generated by Django 3.2.8 on 2021-12-19 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0011_auto_20211212_2211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='user_image',
            new_name='image',
        ),
    ]
