# Generated by Django 3.2.8 on 2021-12-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.CharField(blank=True, choices=[('1', '1/5 stars'), ('2', '2/5 stars'), ('3', '3/5 stars'), ('4', '4/5 stars'), ('5', '5/5 stars')], max_length=30, null=True),
        ),
    ]
