# Generated by Django 3.2.8 on 2022-01-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('unpublished', 'Unpublished'), ('published', 'Published')], default='published', max_length=15),
            preserve_default=False,
        ),
    ]
